name: Dinic CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      env:
        CODEFORCES_LOGIN: ${{ secrets.CODEFORCES_LOGIN }}
        CODEFORCES_PASSWORD: ${{ secrets.CODEFORCES_PASSWORD }}
    - name: install
      run: sh ./utils/firefox/prepare-firefox.sh
    - name: test-cf
      run: cd ./dinic/testing/marbles/ && python3 test.py
      
