name: FFT Benchmark CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  benchmark:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake
      run: cd ./FFT/testing/benchmark/ && cmake .
    - name: make
      run: cd ./FFT/testing/benchmark/ && make
    - name: run
      run: cd ./FFT/testing/benchmark/ && ./TestTeamReferenceFFTBenchmark
