name: Linear independency (Timus.1041) via Gauss elimination CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  timus:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install
      run: pip install orjson selenium webdriver-manager
    - name: test-timus
      env:
        TIMUS_LOGIN: ${{ secrets.TIMUS_LOGIN }}
        TIMUS_PASSWORD: ${{ secrets.TIMUS_PASSWORD }}
      run: bash "./gauss/testing/Timus.1041. Nikifor/test.sh"
